## Core types and data structures for tzutrader.
##
## This module defines the fundamental types used throughout the library:
## - Position: Trading position enum (Stay, Buy, Sell)
## - OHLCV: Open-High-Low-Close-Volume data structure
## - Signal: Trading signal representation
## - StrategyConfig: Strategy configuration
## - TzuTraderError: Base exception type

import std/[tables, times, json, math]

type
  Position* = enum
    ## Trading position action
    Stay  ## Hold current position
    Buy   ## Enter or increase long position
    Sell  ## Exit or decrease long position

  OHLCV* = object
    ## Open-High-Low-Close-Volume bar data
    timestamp*: int64    ## Unix timestamp
    open*: float64       ## Opening price
    high*: float64       ## Highest price
    low*: float64        ## Lowest price
    close*: float64      ## Closing price
    volume*: float64     ## Trading volume

  Signal* = object
    ## Trading signal generated by a strategy
    position*: Position  ## Position action (Stay, Buy, Sell)
    symbol*: string      ## Symbol to trade
    timestamp*: int64    ## Signal generation time (Unix timestamp)
    price*: float64      ## Price at signal generation
    reason*: string      ## Human-readable reason for signal

  StrategyConfig* = object
    ## Strategy configuration parameters
    name*: string                      ## Strategy name
    params*: Table[string, float64]    ## Parameter key-value pairs

  Transaction* = object
    ## Record of an executed trade
    timestamp*: int64    ## Transaction time (Unix timestamp)
    symbol*: string      ## Symbol traded
    action*: Position    ## Buy or Sell action
    quantity*: float64   ## Number of shares/units
    price*: float64      ## Execution price
    commission*: float64 ## Trading commission/fees

  TzuTraderError* = object of CatchableError
    ## Base exception type for tzutrader errors

  DataError* = object of TzuTraderError
    ## Error related to data fetching or processing

  StrategyError* = object of TzuTraderError
    ## Error related to strategy execution

  PortfolioError* = object of TzuTraderError
    ## Error related to portfolio operations

# Helper functions for creating instances

proc newSignal*(position: Position, symbol: string, price: float64, 
                reason: string = ""): Signal =
  ## Create a new trading signal with current timestamp
  result = Signal(
    position: position,
    symbol: symbol,
    timestamp: getTime().toUnix(),
    price: price,
    reason: reason
  )

proc newStrategyConfig*(name: string, 
                       params: Table[string, float64] = initTable[string, float64]()): StrategyConfig =
  ## Create a new strategy configuration
  result = StrategyConfig(name: name, params: params)

proc newTransaction*(symbol: string, action: Position, quantity, price, commission: float64): Transaction =
  ## Create a new transaction record with current timestamp
  result = Transaction(
    timestamp: getTime().toUnix(),
    symbol: symbol,
    action: action,
    quantity: quantity,
    price: price,
    commission: commission
  )

# Conversion and serialization functions

proc `$`*(ohlcv: OHLCV): string =
  ## String representation of OHLCV data
  let dt = fromUnix(ohlcv.timestamp).format("yyyy-MM-dd HH:mm:ss")
  result = "OHLCV(" & dt & 
           " O:" & $ohlcv.open & 
           " H:" & $ohlcv.high & 
           " L:" & $ohlcv.low & 
           " C:" & $ohlcv.close & 
           " V:" & $ohlcv.volume & ")"

proc `$`*(signal: Signal): string =
  ## String representation of Signal
  let dt = fromUnix(signal.timestamp).format("yyyy-MM-dd HH:mm:ss")
  result = "Signal(" & $signal.position & 
           " " & signal.symbol & 
           " @" & $signal.price &
           " at " & dt
  if signal.reason.len > 0:
    result &= " reason: " & signal.reason
  result &= ")"

proc `$`*(tx: Transaction): string =
  ## String representation of Transaction
  let dt = fromUnix(tx.timestamp).format("yyyy-MM-dd HH:mm:ss")
  result = "Transaction(" & $tx.action & 
           " " & $tx.quantity & 
           " " & tx.symbol & 
           " @" & $tx.price &
           " fee:" & $tx.commission &
           " at " & dt & ")"

# JSON serialization

proc toJson*(ohlcv: OHLCV): JsonNode =
  ## Convert OHLCV to JSON
  result = %* {
    "timestamp": ohlcv.timestamp,
    "open": ohlcv.open,
    "high": ohlcv.high,
    "low": ohlcv.low,
    "close": ohlcv.close,
    "volume": ohlcv.volume
  }

proc toJson*(signal: Signal): JsonNode =
  ## Convert Signal to JSON
  result = %* {
    "position": $signal.position,
    "symbol": signal.symbol,
    "timestamp": signal.timestamp,
    "price": signal.price,
    "reason": signal.reason
  }

proc toJson*(tx: Transaction): JsonNode =
  ## Convert Transaction to JSON
  result = %* {
    "timestamp": tx.timestamp,
    "symbol": tx.symbol,
    "action": $tx.action,
    "quantity": tx.quantity,
    "price": tx.price,
    "commission": tx.commission
  }

proc toJson*(config: StrategyConfig): JsonNode =
  ## Convert StrategyConfig to JSON
  result = %* {
    "name": config.name,
    "params": config.params
  }

proc fromJson*(node: JsonNode, T: typedesc[OHLCV]): OHLCV =
  ## Parse OHLCV from JSON
  result = OHLCV(
    timestamp: node["timestamp"].getInt(),
    open: node["open"].getFloat(),
    high: node["high"].getFloat(),
    low: node["low"].getFloat(),
    close: node["close"].getFloat(),
    volume: node["volume"].getFloat()
  )

proc fromJson*(node: JsonNode, T: typedesc[Signal]): Signal =
  ## Parse Signal from JSON
  let posStr = node["position"].getStr()
  let pos = case posStr
    of "Stay": Stay
    of "Buy": Buy
    of "Sell": Sell
    else: Stay
  
  result = Signal(
    position: pos,
    symbol: node["symbol"].getStr(),
    timestamp: node["timestamp"].getInt(),
    price: node["price"].getFloat(),
    reason: node["reason"].getStr()
  )

# Utility functions

proc isValid*(ohlcv: OHLCV): bool =
  ## Check if OHLCV data is valid
  ## Returns false if any price is NaN, negative, or high/low violate constraints
  if ohlcv.open.isNaN or ohlcv.open < 0: return false
  if ohlcv.high.isNaN or ohlcv.high < 0: return false
  if ohlcv.low.isNaN or ohlcv.low < 0: return false
  if ohlcv.close.isNaN or ohlcv.close < 0: return false
  if ohlcv.high < ohlcv.low: return false
  if ohlcv.high < ohlcv.open or ohlcv.high < ohlcv.close: return false
  if ohlcv.low > ohlcv.open or ohlcv.low > ohlcv.close: return false
  return true

proc typicalPrice*(ohlcv: OHLCV): float64 =
  ## Calculate typical price: (High + Low + Close) / 3
  result = (ohlcv.high + ohlcv.low + ohlcv.close) / 3.0

proc trueRange*(curr, prev: OHLCV): float64 =
  ## Calculate true range for ATR calculation
  ## TR = max(high - low, |high - prevClose|, |low - prevClose|)
  let hl = curr.high - curr.low
  let hc = abs(curr.high - prev.close)
  let lc = abs(curr.low - prev.close)
  result = max(hl, max(hc, lc))

proc change*(ohlcv: OHLCV): float64 =
  ## Calculate price change: close - open
  result = ohlcv.close - ohlcv.open

proc changePercent*(ohlcv: OHLCV): float64 =
  ## Calculate percentage change: (close - open) / open * 100
  if ohlcv.open == 0: return 0.0
  result = (ohlcv.close - ohlcv.open) / ohlcv.open * 100.0
