/**
 * @file defs.h
 * @brief Core data structures and types for the tzutrader library
 * 
 * This header defines the fundamental data types used throughout the library,
 * including market data structures (Ohlcv, Tick), trading signals, and
 * enumeration types for trade direction.
 * 
 * These structures are designed to be lightweight and efficient for streaming
 * data processing.
 */

#ifndef DEFS_H
#define DEFS_H

#include <cstdint>
#include <cmath>
#include <ostream>

namespace tzu {

/**
 * @brief Trade direction enumeration
 * 
 * Used to label trades and signals. The NONE value can be used
 * to represent a hold signal (no action).
 */
enum class Side {
    BUY,   ///< Buy signal or long position
    SELL,  ///< Sell signal or short position
    NONE   ///< No action, hold current position
};

/**
 * @brief Trading signal generated by a strategy
 * 
 * Represents a trading decision at a specific point in time.
 * The timestamp represents a Unix timestamp (the scale - seconds,
 * milliseconds, or microseconds - is determined by your data source).
 * 
 * @note The volume field defaults to 1.0 and can be used for
 * custom position sizing logic.
 */
struct Signal {
    int64_t timestamp;  ///< Unix timestamp when signal was generated
    Side side;          ///< Trade direction (BUY/SELL/NONE)
    double price;       ///< Price at which to execute the trade
    double volume;      ///< Volume or size multiplier (default: 1.0)
    
    /**
     * @brief Construct a new Signal object
     * @param ts Timestamp (Unix time)
     * @param s Trade side (BUY/SELL/NONE)
     * @param p Price
     * @param v Volume multiplier
     */
    Signal(int64_t ts = 0, Side s = Side::NONE, double p = 0.0, double v = 1.0)
        : timestamp(ts), side(s), price(p), volume(v) {}
};

/**
 * @brief Field selector for OHLCV data
 * 
 * Used by indicators or strategies that need to access specific fields
 * of OHLCV data. Use with Ohlcv::getFieldValue() to retrieve values.
 */
enum class OhlcvField {
    OPEN,    ///< Opening price
    HIGH,    ///< Highest price in period
    LOW,     ///< Lowest price in period
    CLOSE,   ///< Closing price
    VOLUME   ///< Trading volume
};

/**
 * @brief Open-High-Low-Close-Volume candlestick data
 * 
 * Represents aggregated trading data for a specific time period.
 * This is the most common format for backtesting with candlestick charts.
 * 
 * @note All prices are in the same currency/unit. Volume units depend
 * on the asset being traded.
 */
struct Ohlcv {
    int64_t timestamp;  ///< Unix timestamp for the candle
    double open;        ///< Opening price
    double high;        ///< Highest price during period
    double low;         ///< Lowest price during period
    double close;       ///< Closing price
    double volume;      ///< Trading volume during period
    
    /**
     * Default constructor initializes all fields to zero.
     */
    Ohlcv(int64_t ts = 0, double o = 0.0, double h = 0.0, double l = 0.0,
          double c = 0.0, double v = 0.0)
        : timestamp(ts), open(o), high(h), low(l), close(c), volume(v) {}

    /**
     * Retrieves the value of the specified OHLCV field.
     */
    double getFieldValue(OhlcvField field) const {
        switch (field) {
            case OhlcvField::OPEN: return open;
            case OhlcvField::HIGH: return high;
            case OhlcvField::LOW: return low;
            case OhlcvField::CLOSE: return close;
            case OhlcvField::VOLUME: return volume;
        }
        return std::nan(""); // Should never reach here
    }
};

/**
 * Represents a single tick data point, which includes the timestamp, price,
 * volume, and side of the trade. The `side` field indicates whether the
 * trade was a buy or sell, or if it is not specified (NONE).
 */
struct Tick {
    int64_t timestamp;
    double price = 0.0;
    double volume = 0.0;
    Side side = Side::NONE;
    Tick() = default;
    Tick(int64_t ts, double p, double v, Side s)
        : timestamp(ts), price(p), volume(v), side(s) {}
};

/**
 * Represents a single value data point, which includes the timestamp and a
 * double value. This can be used for indicators or other data that does not
 * fit into the OHLCV or Tick structures.
 */
struct SingleValue {
    int64_t timestamp;
    double value = 0.0;
    SingleValue() = default;
    SingleValue(int64_t ts, double v) : timestamp(ts), value(v) {}
};

/**
 * This enum is intended to communicate the type of data being
 * processed, to enable components to handle different data types
 * appropriately.
 */
enum class DataType {
    OHLCV,
    TICK,
    SINGLE_VALUE,
};

} // namespace tzu

/**
 * Overload the output stream operator for the `Signal` struct to enable
 * easy printing or streaming of signal information.
 */
inline std::ostream& operator<<(std::ostream& os, const tzu::Signal& signal) {
    os << "timestamp: " << signal.timestamp
       << " side: " 
       << (signal.side == tzu::Side::BUY 
               ? "BUY" 
               : signal.side == tzu::Side::SELL 
                ? "SELL" : "NONE")
       << " price: " << signal.price
       << " volume: " << signal.volume << ")";
    return os;
}

/**
 * Represents a trading position, which includes the timestamp of the position,
 * the quantity of the asset held, and the price at which the position was
 * opened. This struct can be used to track open positions in a trading strategy.
 */
struct Position {
    int64_t timestamp;
    double quantity;
    double price;
    Position(int64_t ts = 0, double q = 0.0, double p = 0.0)
        : timestamp(ts), quantity(q), price(p) {}
};

#endif // DEFS_H
