#ifndef DEFS_H
#define DEFS_H

#include <cstdint>
#include <cmath>
#include <ostream>

namespace tzu {

/**
 * The side is used to label a trade as well as a signal.
 * The `NONE` value can be used as a hold signal.
 */
enum class Side {
    BUY,
    SELL,
    NONE
};

/**
 * Represents a trading signal generated by a strategy.  The `timestamp`
 * is the time when the signal was generated. It is intendend to
 * represent a Unix timestamp. The scale (seconds, milliseconds,
 * microseconds) is not fixed and can be determined by the user.
 */
struct Signal {
    int64_t timestamp;
    Side side;
    double price;
    double volume;
    Signal(int64_t ts = 0, Side s = Side::NONE, double p = 0.0, double v = 1.0)
        : timestamp(ts), side(s), price(p), volume(v) {}
};

/**
 * Some indicators or strategy may need to access specific fields of the
 * OHLCV data. This enum can be used to specify which field to access.
 * The `getFieldValue` method in the `Ohlcv` struct can be used to
 * retrieve the value of the specified field.
 */
enum class OhlcvField {
    OPEN,
    HIGH,
    LOW,
    CLOSE,
    VOLUME
};

/**
 * Represents a single Open-High-Low-Close-Volume (OHLCV) data point.
 */
struct Ohlcv {
    int64_t timestamp;
    double open;
    double high;
    double low;
    double close;
    double volume;
    
    /**
     * Default constructor initializes all fields to zero.
     */
    Ohlcv(int64_t ts = 0, double o = 0.0, double h = 0.0, double l = 0.0,
          double c = 0.0, double v = 0.0)
        : timestamp(ts), open(o), high(h), low(l), close(c), volume(v) {}

    /**
     * Retrieves the value of the specified OHLCV field.
     */
    double getFieldValue(OhlcvField field) const {
        switch (field) {
            case OhlcvField::OPEN: return open;
            case OhlcvField::HIGH: return high;
            case OhlcvField::LOW: return low;
            case OhlcvField::CLOSE: return close;
            case OhlcvField::VOLUME: return volume;
        }
        return std::nan(""); // Should never reach here
    }
};

/**
 * Represents a single tick data point, which includes the timestamp, price,
 * volume, and side of the trade. The `side` field indicates whether the
 * trade was a buy or sell, or if it is not specified (NONE).
 */
struct Tick {
    int64_t timestamp;
    double price = 0.0;
    double volume = 0.0;
    Side side = Side::NONE;
    Tick() = default;
    Tick(int64_t ts, double p, double v, Side s)
        : timestamp(ts), price(p), volume(v), side(s) {}
};

/**
 * Represents a single value data point, which includes the timestamp and a
 * double value. This can be used for indicators or other data that does not
 * fit into the OHLCV or Tick structures.
 */
struct SingleValue {
    int64_t timestamp;
    double value = 0.0;
    SingleValue() = default;
    SingleValue(int64_t ts, double v) : timestamp(ts), value(v) {}
};

/**
 * This enum is intended to communicate the type of data being
 * processed, to enable components to handle different data types
 * appropriately.
 */
enum class DataType {
    OHLCV,
    TICK,
    SINGLE_VALUE,
};

} // namespace tzu

/**
 * Overload the output stream operator for the `Signal` struct to enable
 * easy printing or streaming of signal information.
 */
inline std::ostream& operator<<(std::ostream& os, const tzu::Signal& signal) {
    os << "timestamp: " << signal.timestamp
       << " side: " 
       << (signal.side == tzu::Side::BUY 
               ? "BUY" 
               : signal.side == tzu::Side::SELL 
                ? "SELL" : "NONE")
       << " price: " << signal.price
       << " volume: " << signal.volume << ")";
    return os;
}

/**
 * Represents a trading position, which includes the timestamp of the position,
 * the quantity of the asset held, and the price at which the position was
 * opened. This struct can be used to track open positions in a trading strategy.
 */
struct Position {
    int64_t timestamp;
    double quantity;
    double price;
    Position(int64_t ts = 0, double q = 0.0, double p = 0.0)
        : timestamp(ts), quantity(q), price(p) {}
};

#endif // DEFS_H
