#ifndef RUNNERS_H
#define RUNNERS_H

#include "strategies.h"
#include "portfolios.h"
#include "streamers.h"

namespace tzu {

template <class T>
class Runner {
public:
    void run() {
        static_cast<T*>(this)->run();
    }
};

/**
 * BasicRunner takes a strategy, a portfolio and a streamer as template
 * parameters, and allows the user to initialize them with custom
 * parameters. The strategy is responsible for generating trading
 * signals based on the data provided by the streamer, while the
 * portfolio updates its state based on the signals generated by the
 * strategy. The streamer is responsible for providing the data to the
 * strategy. The runner iterates through the data provided by the
 * streamer, updates the strategy with each data point, and updates the
 * portfolio based on the signals generated by the strategy. The runner
 * can also print the portfolio state after each update if the verbose
 * flag is set to true.
 */
template <typename Portfolio, typename Strat, typename Streamer>
class BasicRunner: public Runner<BasicRunner<Portfolio, Strat, Streamer>> {
    Portfolio portfolio;
    Strat strat;
    Streamer streamer;
public:
    BasicRunner(Portfolio& portfolio, Strat& strat, Streamer& streamer)
        : portfolio(portfolio), strat(strat), streamer(streamer) {}
    void run(bool verbose = false) {
        for (const auto& row : streamer) {
            auto sig = strat.update(row);
            portfolio.update(sig);
            if (verbose) std::cout << portfolio << std::endl;
        }
        if (!verbose)
            std::cout << portfolio << std::endl;
    }
};

} // namespace tzu

#endif // RUNNERS_H
