#ifndef RUNNERS_H
#define RUNNERS_H

#include "strategies.h"
#include "portfolios.h"
#include "streamers.h"

namespace tzu {

/**
 * BasicRunner is a more flexible implementation of a backtesting runner. It
 * takes a strategy, a portfolio and a streamer as template parameters, and
 * allows the user to initialize them with custom parameters. The strategy is
 * responsible for generating trading signals based on the data provided by
 * the streamer, while the portfolio updates its state based on the signals
 * generated by the strategy. The streamer is responsible for providing the
 * data to the strategy. The runner iterates through the data provided by
 * the streamer, updates the strategy with each data point, and updates the
 * portfolio based on the signals generated by the strategy. The runner can
 * also print the portfolio state after each update if the verbose flag is set
 * to true.
 */
template <typename Portfolio, typename Strat, typename Streamer>
class BasicRunner {
    Strat strat;
    Portfolio portfolio;
    Streamer streamer;
public:
    BasicRunner(Portfolio portfolio_, Strat strat_, Streamer streamer_)
        : strat(std::move(strat_)), portfolio(std::move(portfolio_)),
            streamer(std::move(streamer_)) {}
    void run(bool verbose = false) {
        for (const auto& row : streamer) {
            auto sig = strat.update(row);
            portfolio.update(sig);
            if (verbose) std::cout << portfolio << std::endl;
        }
        if (!verbose)
            std::cout << portfolio << std::endl;
    }
};

} // namespace tzu

#endif // RUNNERS_H
