## Alert Data Structures for Market Screener
##
## This module defines the core data structures for representing alerts
## generated by the market screener. Alerts represent the latest signals
## from strategies across multiple symbols.
##
## Usage:
## ```nim
## let alert = newAlert(
##   symbol = "AAPL",
##   strategyName = "RSI Mean Reversion",
##   alertType = atBuySignal,
##   price = 178.25,
##   strength = asStrong
## )
## ```

import std/[tables, times, json, strformat, algorithm]
import ../core

type
  AlertType* = enum
    ## Type of alert/signal
    atBuySignal      ## Buy signal generated
    atSellSignal     ## Sell signal generated
    atExitLong       ## Exit long position
    atExitShort      ## Exit short position
    atNeutral        ## No signal

  AlertStrength* = enum
    ## Signal strength assessment
    asWeak           ## Weak signal (low confidence)
    asModerate       ## Moderate signal (medium confidence)
    asStrong         ## Strong signal (high confidence)

  Alert* = object
    ## A single alert generated by the screener
    symbol*: string                      ## Symbol that generated the alert
    strategyName*: string                ## Strategy that generated the alert
    timestamp*: Time                     ## When the alert was generated
    alertType*: AlertType                ## Type of alert (Buy, Sell, etc.)
    strength*: AlertStrength             ## Signal strength
    price*: float64                      ## Price at alert generation
    indicators*: Table[string, float64]  ## Latest indicator values
    metadata*: Table[string, string]     ## Additional context/information
    
  AlertCollection* = object
    ## Collection of alerts from a screener run
    generatedAt*: Time                   ## When the screener was run
    alerts*: seq[Alert]                  ## All alerts generated
    totalSymbols*: int                   ## Total symbols scanned
    totalStrategies*: int                ## Total strategies evaluated

# ============================================================================
# Constructor Functions
# ============================================================================

proc newAlert*(symbol: string, strategyName: string, alertType: AlertType,
               price: float64, strength: AlertStrength = asModerate,
               indicators: Table[string, float64] = initTable[string, float64](),
               metadata: Table[string, string] = initTable[string, string]()): Alert =
  ## Create a new alert with current timestamp
  result = Alert(
    symbol: symbol,
    strategyName: strategyName,
    timestamp: getTime(),
    alertType: alertType,
    strength: strength,
    price: price,
    indicators: indicators,
    metadata: metadata
  )

proc newAlertFromSignal*(signal: Signal, strategyName: string,
                         strength: AlertStrength = asModerate,
                         indicators: Table[string, float64] = initTable[string, float64]()): Alert =
  ## Create an alert from a Signal object
  let alertType = case signal.position
    of Buy: atBuySignal
    of Sell: atSellSignal
    of Stay: atNeutral
  
  var metadata = initTable[string, string]()
  if signal.reason.len > 0:
    metadata["reason"] = signal.reason
  
  result = newAlert(
    symbol = signal.symbol,
    strategyName = strategyName,
    alertType = alertType,
    price = signal.price,
    strength = strength,
    indicators = indicators,
    metadata = metadata
  )
  result.timestamp = fromUnix(signal.timestamp)

proc newAlertCollection*(alerts: seq[Alert], totalSymbols: int, 
                        totalStrategies: int): AlertCollection =
  ## Create a new alert collection
  result = AlertCollection(
    generatedAt: getTime(),
    alerts: alerts,
    totalSymbols: totalSymbols,
    totalStrategies: totalStrategies
  )

# ============================================================================
# Filtering Functions
# ============================================================================

proc filterByType*(alerts: seq[Alert], alertTypes: seq[AlertType]): seq[Alert] =
  ## Filter alerts by alert type(s)
  result = @[]
  for alert in alerts:
    if alert.alertType in alertTypes:
      result.add(alert)

proc filterByStrength*(alerts: seq[Alert], minStrength: AlertStrength): seq[Alert] =
  ## Filter alerts by minimum strength
  result = @[]
  for alert in alerts:
    if alert.strength >= minStrength:
      result.add(alert)

proc filterBySymbol*(alerts: seq[Alert], symbols: seq[string]): seq[Alert] =
  ## Filter alerts by symbol(s)
  result = @[]
  for alert in alerts:
    if alert.symbol in symbols:
      result.add(alert)

proc filterByStrategy*(alerts: seq[Alert], strategies: seq[string]): seq[Alert] =
  ## Filter alerts by strategy name(s)
  result = @[]
  for alert in alerts:
    if alert.strategyName in strategies:
      result.add(alert)

# ============================================================================
# Sorting Functions
# ============================================================================

proc sortByStrength*(alerts: var seq[Alert], ascending: bool = false) =
  ## Sort alerts by strength (descending by default)
  if ascending:
    alerts.sort(proc(a, b: Alert): int = 
      if a.strength < b.strength: -1
      elif a.strength > b.strength: 1
      else: 0
    )
  else:
    alerts.sort(proc(a, b: Alert): int = 
      if a.strength > b.strength: -1
      elif a.strength < b.strength: 1
      else: 0
    )

proc sortBySymbol*(alerts: var seq[Alert]) =
  ## Sort alerts by symbol (alphabetically)
  alerts.sort(proc(a, b: Alert): int = cmp(a.symbol, b.symbol))

proc sortByPrice*(alerts: var seq[Alert], ascending: bool = true) =
  ## Sort alerts by price
  if ascending:
    alerts.sort(proc(a, b: Alert): int = 
      if a.price < b.price: -1
      elif a.price > b.price: 1
      else: 0
    )
  else:
    alerts.sort(proc(a, b: Alert): int = 
      if a.price > b.price: -1
      elif a.price < b.price: 1
      else: 0
    )

proc sortByTimestamp*(alerts: var seq[Alert], ascending: bool = false) =
  ## Sort alerts by timestamp (most recent first by default)
  if ascending:
    alerts.sort(proc(a, b: Alert): int = 
      if a.timestamp < b.timestamp: -1
      elif a.timestamp > b.timestamp: 1
      else: 0
    )
  else:
    alerts.sort(proc(a, b: Alert): int = 
      if a.timestamp > b.timestamp: -1
      elif a.timestamp < b.timestamp: 1
      else: 0
    )

# ============================================================================
# Utility Functions
# ============================================================================

proc topN*(alerts: seq[Alert], n: int): seq[Alert] =
  ## Get top N alerts (assumes already sorted)
  let count = min(n, alerts.len)
  result = alerts[0..<count]

proc countByType*(alerts: seq[Alert]): Table[AlertType, int] =
  ## Count alerts by type
  result = initTable[AlertType, int]()
  for alert in alerts:
    if alert.alertType in result:
      result[alert.alertType] += 1
    else:
      result[alert.alertType] = 1

proc countByStrength*(alerts: seq[Alert]): Table[AlertStrength, int] =
  ## Count alerts by strength
  result = initTable[AlertStrength, int]()
  for alert in alerts:
    if alert.strength in result:
      result[alert.strength] += 1
    else:
      result[alert.strength] = 1

# ============================================================================
# String Representation
# ============================================================================

proc `$`*(alertType: AlertType): string =
  ## String representation of alert type
  case alertType
  of atBuySignal: "BUY"
  of atSellSignal: "SELL"
  of atExitLong: "EXIT LONG"
  of atExitShort: "EXIT SHORT"
  of atNeutral: "NEUTRAL"

proc `$`*(strength: AlertStrength): string =
  ## String representation of alert strength
  case strength
  of asWeak: "WEAK"
  of asModerate: "MODERATE"
  of asStrong: "STRONG"

proc `$`*(alert: Alert): string =
  ## String representation of an alert
  let dt = alert.timestamp.format("yyyy-MM-dd HH:mm:ss")
  result = &"Alert({alert.symbol}, {alert.strategyName}, {alert.alertType}, " &
           &"{alert.strength}, ${alert.price:.2f}, {dt})"

# ============================================================================
# JSON Serialization
# ============================================================================

proc toJson*(alert: Alert): JsonNode =
  ## Convert Alert to JSON
  result = %* {
    "symbol": alert.symbol,
    "strategy": alert.strategyName,
    "timestamp": alert.timestamp.toUnix(),
    "type": $alert.alertType,
    "strength": $alert.strength,
    "price": alert.price,
    "indicators": alert.indicators,
    "metadata": alert.metadata
  }

proc toJson*(collection: AlertCollection): JsonNode =
  ## Convert AlertCollection to JSON
  var alertsJson = newJArray()
  for alert in collection.alerts:
    alertsJson.add(alert.toJson())
  
  result = %* {
    "generated_at": collection.generatedAt.toUnix(),
    "total_symbols": collection.totalSymbols,
    "total_strategies": collection.totalStrategies,
    "total_alerts": collection.alerts.len,
    "alerts": alertsJson
  }
